# Generated by Django 2.2.7 on 2019-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('contact_no', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=120)),
            ],
        ),
    ]
