# Generated by Django 2.2.7 on 2020-05-12 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0002_auto_20200512_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cars'),
            preserve_default=False,
        ),
    ]
