# Generated by Django 2.2.7 on 2020-05-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
