# Generated by Django 2.2.7 on 2020-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0004_auto_20200512_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_img',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
