# Generated by Django 2.2.7 on 2020-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0005_product_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_text',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
