# Generated by Django 2.2.7 on 2020-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0006_product_order_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('list', models.CharField(max_length=120)),
            ],
        ),
    ]
