# Generated by Django 2.2.7 on 2020-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0007_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='list',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
