# Generated by Django 2.2.7 on 2020-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0008_auto_20200607_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
