# Generated by Django 2.2.7 on 2020-06-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0014_auto_20200619_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ema',
        ),
    ]
