# Generated by Django 2.2.7 on 2020-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0016_auto_20200629_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
