# Generated by Django 2.2.7 on 2020-07-22 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0017_delete_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='list',
        ),
        migrations.RemoveField(
            model_name='price',
            name='list2',
        ),
        migrations.RemoveField(
            model_name='price',
            name='list3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='list4',
        ),
        migrations.RemoveField(
            model_name='price',
            name='list5',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='img',
            field=models.ImageField(default=1, upload_to='service_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
