# Generated by Django 2.2.7 on 2021-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0019_auto_20210425_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='star',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
