# Generated by Django 2.2.7 on 2021-05-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0022_price_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='testimonial')),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='head',
            field=models.CharField(default='This is heading', max_length=50),
        ),
    ]
