# Generated by Django 2.2.7 on 2021-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quert', '0024_client_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='DOC')),
            ],
        ),
    ]
